USE CATALOGOS
GO

CREATE TABLE tp_brkPayments(
	brkp_id INT NOT NULL IDENTITY(1,1)
	, brkp_Eid INT NOT NULL CONSTRAINT DEF_brkp_eid DEFAULT(0)
	, brkp_nemp INT NOT NULL CONSTRAINT DEF_brkp_nemp DEFAULT(0)
	, brkp_payUser VARCHAR(15) NOT NULL CONSTRAINT DEF_brkp_payUser DEFAULT('')
	, brkp_cUser VARCHAR(15) NOT NULL CONSTRAINT DEF_brkp_cUser DEFAULT('')
	, brkp_amount DECIMAL(18,4) NOT NULL CONSTRAINT DEF_brkp_amount DEFAULT('')
	, brkp_cDate DATETIME NOT NULL CONSTRAINT DEF_brkp_cDate DEFAULT(GETDATE())
	, brkp_paymentApp BIT NOT NULL CONSTRAINT DEF_brkp_paymentApp DEFAULT(1)
	, brkp_codeSvaApp VARCHAR(20) NOT NULL CONSTRAINT DEF_brkp_codeSvaApp DEFAULT('')
)